loremipsum.settings:
    type: config_object
    label: 'Lorem ipsum settings'
    mapping:
        loremipsum:
            type: mapping
            mapping:
                page_title:
                    type: text
                    label: 'Lorem ipsum generatos page title:'
                source_text:
                    type: text
                    label: 'Source text for lorem ipsum generation:'
                    
block.settings.loremipsum_block:
    type: block_settings
    label: 'Lorem ipsum block'
    mapping:
        loremimpsum_block_settings: