<?php

/**
 * @file
 * Contains content_entity_ejemplo.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_entity_ejemplo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_entity_ejemplo module.
    case 'help.page.content_entity_ejemplo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Entidades, Content entities y configuracion entities') . '</p>';
      return $output;

    default:
  }
}
