<?php

/**
 * @file
 * Contains loremipsum.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function loremipsum_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the loremipsum module.
    case 'help.page.loremipsum':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modulo para la generacion de texto tipo lorem ipsum') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme
 */

function loremipsum_theme($existing, $type, $theme, $path) {
    $variables = array(
        'loremipsum' => array(
            'variables' => array(
                'source_text' => NULL,
            ),
            'template' => 'loremipsum',
        ),
    );
    return $variables;
}

/**
 * Template preprocess function for Lorem ipsum
 *
 * @param variables
 *   An associative array containing:
 *   - source_text
 */
function template_preprocess_loremipsum(&$variables) {
  $punctuation = array('. ', '! ', '? ', '... ', ': ', '; ');
  for ($i = 0; $i < count($variables['source_text']); $i++) {
    $big_text = explode('. ', $variables['source_text'][$i]);
    for ($j = 0; $j < count($big_text)-1; $j++) {
      $big_text[$j] .= $punctuation[floor(mt_rand(0, count($punctuation)-1))];
    }
    $variables['source_text'][$i] = implode('', $big_text);
  }
}
        
